#!/usr/bin/env sh

DAEMON_NAME="$0"
PYTHON_PATH="/etc/init.d"

daemon_msg() {
    printf "%s: %s\n" "$DAEMON_NAME" "$1"
}

err_msg() {
    printf "%s:\n%s\n" "$DAEMON_NAME" "$1" >&2
    exit 1
}

simple_ping_test() {
    daemon_msg "Doing a simple ping test..."
    ping -c1 8.8.8.8 || (daemon_msg "Couldn't ping. Waiting 5s before trying again." && sleep 5 && ping -c1 8.8.8.8) || err_msg "Failed to ping."
    echo # Looks slightly tidier
}

start() {
    simple_ping_test
    daemon_msg "Calling Python startup thingy..."
    $PYTHON_PATH/onstart.py
}

stop() {
    simple_ping_test
    daemon_msg "Calling Python shutdown thingy"
    $PYTHON_PATH/onstop.py
}

restart() {
    err_msg "This daemon can't sensibly restart."
}

case "$1" in
    start|stop|restart)
        "$1";;
    reload)
        restart;;
    *)
        err_msg "Usage: $0 {start|stop|restart|reload}"
esac

