#!/bin/sh

DAEMON_NAME="$0"
PYTHON_PATH="/etc/init.d"

daemon_msg() {
    printf "%s: %s\n" "$DAEMON_NAME" "$1"
}

err_msg() {
    printf "%s:\n%s\n" "$DAEMON_NAME" "$1" >&2
    exit 1
}

start() {
    daemon_msg "Caling Python startup thingy..."
    $PYTHON_PATH/onstart.py
}

stop() {
    daemon_msg "Calling Python shutdown thingy"
    $PYTHON_PATH/onstop.py
}

restart() {
    err_msg "This daemon can't sensibly restart."
}

case "$1" in
    start|stop|restart)
        "$1";;
    reload)
        restart;;
    *)
        err_msg "Usage: $0 {start|stop|restart|reload}"
esac

